Fix Clippy warnings by adding #[allow(deprecated)]
The `rgb` crate has deprecated ComponentSlice and builds issue
this warning:

```
error: use of deprecated trait `rgb::ComponentSlice`: use `bytemuck::cast_slice()` instead
   --> esp-hal-smartled/src/lib.rs:211:17
    |
211 |     Color: rgb::ComponentSlice<u8>,
    |                 ^^^^^^^^^^^^^^
```

This is reference in
https://github.com/esp-rs/esp-hal-community/issues/72.

However `rgb@0.8` does not implement Pod for Grb<T>, so this crate
cannot migrate away from `ComponentSlice`. Here are two tests to verify
this:

```rs
fn test_rgb_u8_is_pod_works() {
    let px = rgb::Rgb { r: 1u8, g: 2, b: 3 };
    let bytes: &[u8] = rgb::bytemuck::bytes_of(&px);
    assert_eq!(bytes, &[1, 2, 3]);
}

fn grb_u8_is_pod_fails_build() {
    let px = rgb::Grb { g: 1u8, r: 2, b: 3 };
    let bytes: &[u8] = rgb::bytemuck::bytes_of(&px);
    assert_eq!(bytes, &[1, 2, 3]);
}
```

`grb_u8_is_pod_fails_build()` fails to build in the rgb v0.8 branch, but
it does compile in main (AKA 0.9). So, this project can migrate away
from the deprecated ComponentSlice trait as soon as we roll the `rgb`
crate to 0.9 or later.

This change adds a few `#[allow(deprecated)]` annotations which fixes
the clippy CI tasks in GitHub.